// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgWgIS399yG-rUzpKbqxrEk9bcV2WS-Es',
    appId: '1:99530883410:android:a392295c7aadc2a74c3a8b',
    messagingSenderId: '99530883410',
    projectId: 'lekture-ai',
    storageBucket: 'lekture-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYWUheNx0LbSM6gTxD7JDCI8RFrw_DdW8',
    appId: '1:99530883410:ios:cbc90d5f75e591244c3a8b',
    messagingSenderId: '99530883410',
    projectId: 'lekture-ai',
    storageBucket: 'lekture-ai.firebasestorage.app',
    iosClientId: '99530883410-m7aaku38jm5ibbgbiu40isl4v4huvkp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.lektureAi',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvaSmXDsUbjWilxu37hjno95c4y4ccoR8',
    appId: '1:99530883410:web:be6bf1fabb1b374b4c3a8b',
    messagingSenderId: '99530883410',
    projectId: 'lekture-ai',
    authDomain: 'lekture-ai.firebaseapp.com',
    storageBucket: 'lekture-ai.firebasestorage.app',
    measurementId: 'G-VG7HXFYNWW',
  );

}